server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
okta:
  client:
    orgUrl: https://dev-497881.oktapreview.com
  oauth2:
    redirectUri: /authorization-code/callback
    issuer: https://dev-497881.oktapreview.com/oauth2/default
    clientSecret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    clientId: 0oat0pm28wTzcJmey0h7

security:
  oauth2:
    client:
      # Redirect to your local page and render the widget
      userAuthorizationUri: http://localhost:${server.port}/login
      scope: openid profile email okta.users.manage.self
